"""dbt project connector for lineage extraction."""
import json
from pathlib import Path
from typing import AsyncIterator, Optional
from dataclasses import dataclass

from .base import (
    BaseConnector,
    ColumnMetadata,
    DatasetMetadata,
    TransformationMetadata,
    ConnectionError as ConnectorConnectionError,
    DiscoveryError,
)


@dataclass
class DbtModel:
    """Represents a dbt model."""
    unique_id: str
    name: str
    schema_name: str
    database: str
    raw_sql: str
    compiled_sql: Optional[str]
    depends_on: list[str]
    columns: list[ColumnMetadata]
    tags: list[str]
    materialized: str  # 'view', 'table', 'incremental', 'ephemeral'


class DbtConnector(BaseConnector):
    """
    dbt project connector.

    Extracts lineage from dbt projects by:
    1. Reading dbt manifest.json (generated by dbt compile/run)
    2. Parsing model SQL files
    3. Extracting dependencies from ref() and source() macros
    """

    def __init__(self, connection_config: dict[str, any]):
        """
        Initialize dbt connector.

        Args:
            connection_config: Should contain:
                - project_dir: Path to dbt project directory
                - manifest_path: Optional path to manifest.json
                - profiles_dir: Optional path to profiles directory
        """
        super().__init__(connection_config)
        self.project_dir = Path(connection_config['project_dir'])
        self.manifest_path = connection_config.get(
            'manifest_path',
            self.project_dir / 'target' / 'manifest.json'
        )
        self.manifest: Optional[dict] = None

    async def test_connection(self) -> bool:
        """
        Test if dbt project is valid.

        Returns:
            True if valid dbt project
        """
        try:
            # Check if project directory exists
            if not self.project_dir.exists():
                raise ConnectorConnectionError(
                    f"dbt project directory not found: {self.project_dir}"
                )

            # Check for dbt_project.yml
            dbt_project_file = self.project_dir / 'dbt_project.yml'
            if not dbt_project_file.exists():
                raise ConnectorConnectionError(
                    f"dbt_project.yml not found in {self.project_dir}"
                )

            # Try to load manifest if it exists
            if Path(self.manifest_path).exists():
                self._load_manifest()
            else:
                # Manifest doesn't exist yet - this is okay, can still parse SQL files
                pass

            return True

        except Exception as e:
            raise ConnectorConnectionError(f"dbt connection test failed: {e}") from e

    async def discover_datasets(self) -> AsyncIterator[DatasetMetadata]:
        """
        Discover dbt models as datasets.

        Yields:
            DatasetMetadata for each dbt model
        """
        try:
            # Load manifest
            if not self.manifest:
                self._load_manifest()

            if not self.manifest:
                raise DiscoveryError("dbt manifest.json not found. Run 'dbt compile' first.")

            # Extract models from manifest
            models = self.manifest.get('nodes', {})

            for unique_id, node in models.items():
                # Only process models (not tests, seeds, etc.)
                if not node.get('resource_type') == 'model':
                    continue

                # Extract model metadata
                model = self._parse_model_node(node)

                # Build dataset metadata
                yield DatasetMetadata(
                    fully_qualified_name=f"dbt.{model.schema_name}.{model.name}",
                    name=model.name,
                    schema_name=model.schema_name,
                    type=self._get_dataset_type(model.materialized),
                    columns=model.columns,
                    metadata={
                        'source_type': 'dbt',
                        'unique_id': model.unique_id,
                        'materialized': model.materialized,
                        'tags': model.tags,
                        'database': model.database,
                    }
                )

        except Exception as e:
            raise DiscoveryError(f"Failed to discover dbt models: {e}") from e

    async def discover_transformations(self) -> AsyncIterator[TransformationMetadata]:
        """
        Extract transformation logic from dbt models.

        Yields:
            TransformationMetadata for each dbt model
        """
        try:
            # Load manifest
            if not self.manifest:
                self._load_manifest()

            if not self.manifest:
                raise DiscoveryError("dbt manifest.json not found. Run 'dbt compile' first.")

            # Extract models
            models = self.manifest.get('nodes', {})

            for unique_id, node in models.items():
                if not node.get('resource_type') == 'model':
                    continue

                model = self._parse_model_node(node)

                # Extract source tables
                source_tables = self._extract_source_tables(node)

                # Use compiled SQL if available, otherwise raw SQL
                sql = model.compiled_sql or model.raw_sql

                yield TransformationMetadata(
                    source_fqns=source_tables,
                    target_fqn=f"dbt.{model.schema_name}.{model.name}",
                    code=sql,
                    language='sql',
                    dialect=self._get_dialect(),
                    type=model.materialized
                )

        except Exception as e:
            raise DiscoveryError(f"Failed to discover dbt transformations: {e}") from e

    async def close(self) -> None:
        """Close connection and cleanup resources."""
        # No resources to clean up for dbt
        pass

    def _load_manifest(self) -> None:
        """Load dbt manifest.json file."""
        manifest_path = Path(self.manifest_path)

        if not manifest_path.exists():
            return

        with open(manifest_path, 'r') as f:
            self.manifest = json.load(f)

    def _parse_model_node(self, node: dict) -> DbtModel:
        """Parse dbt model node from manifest."""
        # Extract columns
        columns = []
        for col_name, col_info in node.get('columns', {}).items():
            columns.append(ColumnMetadata(
                name=col_name,
                data_type=col_info.get('data_type', 'unknown'),
                ordinal_position=len(columns) + 1,
                is_nullable=True,  # dbt doesn't always have this info
                is_primary_key=False
            ))

        return DbtModel(
            unique_id=node.get('unique_id', ''),
            name=node.get('name', ''),
            schema_name=node.get('schema', 'public'),
            database=node.get('database', ''),
            raw_sql=node.get('raw_sql', ''),
            compiled_sql=node.get('compiled_sql'),
            depends_on=node.get('depends_on', {}).get('nodes', []),
            columns=columns,
            tags=node.get('tags', []),
            materialized=node.get('config', {}).get('materialized', 'view')
        )

    def _extract_source_tables(self, node: dict) -> list[str]:
        """
        Extract source table FQNs from dbt model dependencies.

        Args:
            node: dbt model node from manifest

        Returns:
            List of source table FQNs
        """
        sources = []

        # Get depends_on from node
        depends_on = node.get('depends_on', {}).get('nodes', [])

        for dep_id in depends_on:
            # dep_id format: "model.project.model_name" or "source.project.source_name.table_name"
            parts = dep_id.split('.')

            if parts[0] == 'source' and len(parts) >= 4:
                # Source table: source.project.source_name.table_name
                source_name = parts[2]
                table_name = parts[3]
                sources.append(f"{source_name}.{table_name}")

            elif parts[0] == 'model' and len(parts) >= 3:
                # dbt model dependency
                model_name = parts[2]
                # Look up model schema from manifest
                if self.manifest:
                    dep_node = self.manifest.get('nodes', {}).get(dep_id, {})
                    schema = dep_node.get('schema', 'public')
                    sources.append(f"dbt.{schema}.{model_name}")
                else:
                    sources.append(f"dbt.{model_name}")

        return sources

    def _get_dataset_type(self, materialized: str) -> str:
        """Convert dbt materialization to dataset type."""
        mapping = {
            'view': 'view',
            'table': 'table',
            'incremental': 'table',
            'ephemeral': 'view',
            'materialized_view': 'materialized_view'
        }
        return mapping.get(materialized, 'view')

    def _get_dialect(self) -> str:
        """
        Get SQL dialect from dbt profile.

        Returns:
            SQL dialect (postgres, snowflake, bigquery, etc.)
        """
        # Try to read from manifest metadata
        if self.manifest:
            metadata = self.manifest.get('metadata', {})
            adapter_type = metadata.get('adapter_type', 'postgres')
            return adapter_type

        # Default to postgres
        return 'postgres'


class DbtProjectParser:
    """
    Parser for dbt projects without manifest.

    Parses dbt models directly from SQL files when manifest is not available.
    """

    def __init__(self, project_dir: Path):
        """Initialize parser."""
        self.project_dir = project_dir
        self.models_dir = project_dir / 'models'

    def discover_models(self) -> list[Path]:
        """Discover all .sql model files in project."""
        if not self.models_dir.exists():
            return []

        # Recursively find all .sql files
        return list(self.models_dir.rglob('*.sql'))

    def parse_model_refs(self, sql_content: str) -> list[str]:
        """
        Parse ref() and source() macros from dbt model SQL.

        Args:
            sql_content: dbt model SQL content

        Returns:
            List of referenced models/sources
        """
        import re

        refs = []

        # Match ref('model_name') or ref("model_name")
        ref_pattern = r"ref\s*\(\s*['\"]([^'\"]+)['\"]\s*\)"
        refs.extend(re.findall(ref_pattern, sql_content))

        # Match source('source_name', 'table_name')
        source_pattern = r"source\s*\(\s*['\"]([^'\"]+)['\"]\s*,\s*['\"]([^'\"]+)['\"]\s*\)"
        sources = re.findall(source_pattern, sql_content)
        refs.extend([f"{src}.{tbl}" for src, tbl in sources])

        return refs
